packages:
  - .
  - ./package/core
  - ./example
  - ./example/cdk

allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  core-js: false
  esbuild: false
  protobufjs: false
  unrs-resolver: false

blockExoticSubdeps: true

minimumReleaseAge: 10080 # 7 days in minutes
minimumReleaseAgeExclude:
  - pnpm@11.17.0
  - file-type@21.3.1 || 21.3.2
  - brace-expansion@5.0.8

overrides:
  eslint-import-resolver-typescript: '^4.4.5'
  semver: '>=7'

  '@eslint/js': ^10
  "@types/node": ^24
  typescript-eslint: ^8
  eslint: ^10
  brace-expansion@<=5.0.7: ^5.0.8
  file-type@>=13.0.0 <21.3.1: ^21.3.1
  file-type@>=20.0.0 <=21.3.1: ^21.3.2

trustPolicy: no-downgrade

injectWorkspacePackages: true
