packages:
  - ./package/core
  - ./example
  - ./example/cdk

autoInstallPeers: true

enablePrePostScripts: true

legacyPeerDeps: true
overrides:
  file-type@>=13.0.0 <21.3.1: '>=21.3.1'

strictPeerDependencies: false
