packages:
  - ./package/core
  - ./example
  - ./example/cdk

autoInstallPeers: true

enablePrePostScripts: true

legacyPeerDeps: true

overrides:
  diff@<8.0.3: '>=8.0.3'
  seroval@<1.4.1: '>=1.4.1'
  seroval@<=1.4.0: '>=1.4.1'

strictPeerDependencies: false
