packages:
  - ./package/core
  - ./example
  - ./example/cdk

autoInstallPeers: true

enablePrePostScripts: true

legacyPeerDeps: true

overrides:
  diff@<8.0.3: '>=8.0.3'

strictPeerDependencies: false
